### ISSUE TITLE
Sohrab-NN code?

### ISSUE THREAD

**Issue by Hrant-Khachatrian** [mpsilfve/finer-data#1]
Dear authors,

You have used the neural model from the paper "Deep Exhaustive Model for Nested Named Entity Recognition". How did you get the code for that model? Did you implement it from scratch? 

Thanks

**Comment by ruokolt** [comment]
Hi,

To our knowledge the implementation is not publicly available anywhere. Therefore, we contacted the first author, Mohammad Golam Sohrab, directly and he ran his model on our data. He might be willing to share the implementation also, you can contact him at sohrab.mohammad@aist.go.jp.

Hope this helps,

-Teemu

**Comment by Hrant-Khachatrian** [comment]
Thanks!

**Comment by JackySnake** [comment]
The code of "Deep Exhaustive Model for Nested Named Entity Recognition" may be avaliable in https://github.com/thecharm/boundary-aware-nested-ner/tree/master/deep_exhaustive_model.
